BEING_LOGICAL = (
    "Underwater bubbles and raindrops are total opposites of each other.",
    "If you buy an eraser you are literally paying for your mistakes.",
    "humans colonize the moon, it will probably attract retirement homes as the weaker gravity will allow the elderly to feel stronger.",
    "The Person you care for most has the potential to destroy you the most.",
    "Any video with “wait for it” in the title is simply too long.",
    "Your age in years is how many times you’ve circled the Sun, but your age in months is how many times the Moon has circled you.",
    "Biting your tongue while eating is a perfect example of how you can still screw up, even with decades of experience.",
    "Saying that your home is powered by a wireless Nuclear fusion reactor that is 93 Million miles away sounds way cooler than just saying you have solar panels on your roof.",
    "The most crushing feeling is when someone smiles at you on the street and you don’t react fast enough to smile back.",
    "Teeth constantly require maintenance to prevent their decay when alive, and yet they manage to survive for thousands of years buried as fossils.",
    "A folder is for things that you don't want to fold.",
    "Waking up in the morning sometimes feels like resuming a shitty movie you decided to quit watching.",
    "If everything goes smoothly, you probably won't remember today.",
    "When you meet new people in real life, you unlock more characters for your dream world.",
    "Maybe if they renamed sunscreen to “anti-cancer cream” more people would wear it.",
    "200 years ago, people would never have guessed that humans in the future would communicate by silently tapping on glass.",
    "Parents worry about what their sons download and worry about what their daughters upload.",
    "It's crazy how you can be the same age as someone, but at a completely different stage in your life.",
    "When you think you wanna die, you really don't wanna die, you just don't wanna live like this.",
    "Technically, no one has ever been in an empty room.",
    "An onion is the bass player of food. You would probably not enjoy it solo, but you’d miss it if it wasn’t there.",
    "We run everywhere in videogames because we're too lazy to walk, but In real life we walk everywhere because we're too lazy to run.",
    "Every single decision you ever made has brought you to read this sentence.",
    "The word 'quiet' is often said very loud.",
    "Everybody wants you to work hard, but nobody wants to hear about how hard you work.",
    "We brush our teeth with hair on a stick and brush our hair with teeth on a stick.",
    "No one remembers your awkward moments but they’re too busy remembering their own.",
    "Dumb people try to say simple ideas as complex as possible while smart people try to say complex ideas as simple as possible.",
    "Some people think they're better than you because they grew up richer. Some people think they're better than you because they grew up poorer.",
    "The biggest irony is that computers & mobiles were invented to save out time!",
    "After honey was first discovered, there was likely a period where people were taste testing any available slime from insects.",
    "You know you’re getting old when your parents start disappointing you, instead of you disappointing them.",
    "Humans are designed to learn through experience yet the education system has made it so we get no experience.",
    "By focusing on blinking, you blink slower... Same for breathing.",
    "Drivers in a hurry to beat traffic usually cause the accidents which create the traffic they were trying to avoid.",
    "Characters that get married in fiction were literally made for each other.",
    "Babies are a clean hard drive that can be programmed with any language.",
    "There could be a miracle drug that cures every disease to man, that we'll never know about because it doesn't work on rats.",
    "Rhinos evolved to grow a horn for protection, but it's what's making them go extinct.",
    "Maybe we don't find time travelers because we all die in 25-50 years.",
    "Sleep is the trial version of death, It even comes with ads based on your activity.",
    "The most unrealistic thing about Spy movies is how clean the air ventilation system is!",
    "In games we play through easy modes to unlock hard modes. In life we play through hard modes to unlock easy modes.",
    "Silent people seem smarter than loud people, because they keep their stupid thoughts to themselves.",
    "If Greenland actually turns green, we're all screwed.",
    "If someone says clever things in your dream, it actually shows your own cleverness.",
    "Famous movie quotes are credited to the actor and not the actual writer who wrote them.",
    "No one actually teaches you how to ride a bicycle. They just hype you up until you work it out.",
    "Ask yourself why the the brain ignores the second the.",
    "You’ve probably forgot about 80% of your entire life and most of the memories you do remember are not very accurate to what actually happened.",
    "It will be a lot harder for kids to win against their parents in video games in the future.",
    "Everyone has flaws, if you don't recognize yours, you have a new one.",
    "Raising a child is training your replacement.",
    "'O'pen starts with a Closed circle, and 'C'lose starts with an open circle.",
    "There's always someone who hated you for no reason, and still does.",
    "After popcorn was discovered, there must have been a lot of random seeds that were roasted to see if it would have the same effect.",
    "The more important a good night's sleep is, the harder it is to fall asleep.",
    "Blessed are those that can properly describe the type of haircut they want to a new stylist.",
    "Too many people spend money they haven't earned, to buy things they don't want, to impress people they don't like!",
    "Theme park employees must be good at telling the difference between screams of horror and excitement.",
    "6 to 6:30 feels more half-an-hour than 5:50 to 6:20",
    "Getting your password right on the last login attempt before lockout is the closest thing to disarming a bomb at the last minute that most of us will experience.",
    "Listening to podcasts before bed is the adult version of story-time.",
    "If all criminals stopped robbing then the security industry would fall in which they could then easily go back to robbing.",
    "A ton of whales is really only like half a whale.",
    "When you get old, the old you is technically the new you, and your young self is the old you.",
    "You probably won't find many negative reviews of parachutes on the Internet.",
    "We show the most love and admiration for people when they're no longer around to appreciate it.",
    "We've practiced sleeping thousands of times, yet can't do it very well or be consistent.",
    "Humans are more enthusiastic about moving to another planet with hostile environment than preserving earth - the planet they are perfectly shaped for.",
    "The happiest stage of most people's lives is when their brains aren't fully developed yet.",
    "The most effective alarm clock is a full bladder.",
    "You probably just synchronized blinks with millions of people.",
    "Since we test drugs on animals first, rat medicine must be years ahead of human medicine.",
    "Night before a day off is more satisfying than the actual day off.",
    "We put paper in a folder to keep it from folding.",
    "Somewhere, two best friends are meeting for the first time.",
    "Our brain simultaneously hates us, loves us, doesn't care about us, and micromanages our every move.",
    "Being a male is a matter of birth. Being a man is a matter of age. But being a gentleman is a matter of choice.",
    "Soon the parents will be hiding their social account from their kids rather than kids hiding their accounts from the parents.",
    "Wikipedia is what the internet was meant to be.",
    "A theme park is the only place that you can hear screams in the distance and not be concerned.",
    "A wireless phone charger offers less freedom of movement than a wired one.",
    "If you repeatedly criticize someone for liking something you don't, they won't stop liking it. They'll stop liking you.",
    "Somewhere there is a grandmother, whose grandson really is the most handsome boy in the world.",
    "If someday human teleportation becomes real, people will still be late for work.",
    "The first humans who ate crabs must have been really hungry to try and eat an armored sea spider",
    "Doing something alone is kind of sad, but doing it solo is cool af.",
    "Your brain suddenly becomes perfect at proofreading after you post something.",
    "There's always that one song in your playlist that you always skip but never remove.",
    "Kids next century will probably hate us for taking all the good usernames.",
    "Bubbles are to fish what rain is to humans.",
    "The more people you meet, the more you realise and appreciate how well your parents raised you.",
    "A comma is a short pause, a coma is a long pause.",
    "Someday you will either not wake up or not go to sleep.",
    "Bermuda Triangle might be the exit portal of this simulation.",
    "If we put solar panels above parking lots, then our cars wouldn't get hot and we would have a lot of clean energy.",
)

GDNIGHT = [
    "`Good night keep your dreams alive`",
    "`Night, night, to a dear friend! May you sleep well!`",
    "`May the night fill with stars for you. May counting every one, give you contentment!`",
    "`Wishing you comfort, happiness, and a good night’s sleep!`",
    "`Now relax. The day is over. You did your best. And tomorrow you’ll do better. Good Night!`",
    "`Good night to a friend who is the best! Get your forty winks!`",
    "`May your pillow be soft, and your rest be long! Good night, friend!`",
    "`Let there be no troubles, dear friend! Have a Good Night!`",
    "`Rest soundly tonight, friend!`",
    "`Have the best night’s sleep, friend! Sleep well!`",
    "`Have a very, good night, friend! You are wonderful!`",
    "`Relaxation is in order for you! Good night, friend!`",
    "`Good night. May you have sweet dreams tonight.`",
    "`Sleep well, dear friend and have sweet dreams.`",
    "`As we wait for a brand new day, good night and have beautiful dreams.`",
    "`Dear friend, I wish you a night of peace and bliss. Good night.`",
    "`Darkness cannot last forever. Keep the hope alive. Good night.`",
    "`By hook or crook you shall have sweet dreams tonight. Have a good night, buddy!`",
    "`Good night, my friend. I pray that the good Lord watches over you as you sleep. Sweet dreams.`",
    "`Good night, friend! May you be filled with tranquility!`",
    "`Wishing you a calm night, friend! I hope it is good!`",
    "`Wishing you a night where you can recharge for tomorrow!`",
    "`Slumber tonight, good friend, and feel well rested, tomorrow!`",
    "`Wishing my good friend relief from a hard day’s work! Good Night!`",
    "`Good night, friend! May you have silence for sleep!`",
    "`Sleep tonight, friend and be well! Know that you have done your very best today, and that you will do your very best, tomorrow!`",
    "`Friend, you do not hesitate to get things done! Take tonight to relax and do more, tomorrow!`",
    "`SO JAO BAHUT RAT HO GAYI KAL TUMSE LIPAT LUNGA`",
    "`Friend, I want to remind you that your strong mind has brought you peace, before. May it do that again, tonight! May you hold acknowledgment of this with you!`",
    "`Wishing you a calm, night, friend! Hoping everything winds down to your liking and that the following day meets your standards!`",
    "`May the darkness of the night cloak you in a sleep that is sound and good! Dear friend, may this feeling carry you through the next day!`",
    "`Friend, may the quietude you experience tonight move you to have many more nights like it! May you find your peace and hold on to it!`",
    "`May there be no activity for you tonight, friend! May the rest that you have coming to you arrive swiftly! May the activity that you do tomorrow match your pace and be all of your own making!`",
    "`When the day is done, friend, may you know that you have done well! When you sleep tonight, friend, may you view all the you hope for, tomorrow!`",
    "`When everything is brought to a standstill, friend, I hope that your thoughts are good, as you drift to sleep! May those thoughts remain with you, during all of your days!`",
    "`Every day, you encourage me to do new things, friend! May tonight’s rest bring a new day that overflows with courage and exciting events!`",
]

GDMORNING = [
    "`Life is full of uncertainties. But there will always be a sunrise after every sunset. Good morning!`",
    "`It doesn’t matter how bad was your yesterday. Today, you are going to make it a good one. Wishing you a good morning!`",
    "`If you want to gain health and beauty, you should wake up early. Good morning!`",
    "`May this morning offer you new hope for life! May you be happy and enjoy every moment of it. Good morning!`",
    "`May the sun shower you with blessings and prosperity in the days ahead. Good morning!`",
    "`Every sunrise marks the rise of life over death, hope over despair and happiness over suffering. Wishing you a very enjoyable morning today!`",
    "`Wake up and make yourself a part of this beautiful morning. A beautiful world is waiting outside your door. Have an enjoyable time!`",
    "`Welcome this beautiful morning with a smile on your face. I hope you’ll have a great day today. Wishing you a very good morning!`",
    "`You have been blessed with yet another day. What a wonderful way of welcoming the blessing with such a beautiful morning! Good morning to you!`",
    "`Waking up in such a beautiful morning is a guaranty for a day that’s beyond amazing. I hope you’ll make the best of it. Good morning!`",
    "`Nothing is more refreshing than a beautiful morning that calms your mind and gives you reasons to smile. Good morning! Wishing you a great day.`",
    "`Another day has just started. Welcome the blessings of this beautiful morning. Rise and shine like you always do. Wishing you a wonderful morning!`",
    "`Wake up like the sun every morning and light up the world your awesomeness. You have so many great things to achieve today. Good morning!`",
    "`UTH GAYA RE HEHEHEH, TERA GF KI DETAILS LE LIYA MAINE HEHE`",
    "`A new day has come with so many new opportunities for you. Grab them all and make the best out of your day. Here’s me wishing you a good morning!`",
    "`The darkness of night has ended. A new sun is up there to guide you towards a life so bright and blissful. Good morning dear!`",
    "`Wake up, have your cup of morning tea and let the morning wind freshen you up like a happiness pill. Wishing you a good morning and a good day ahead!`",
    "`Sunrises are the best; enjoy a cup of coffee or tea with yourself because this day is yours, good morning! Have a wonderful day ahead.`",
    "`A bad day will always have a good morning, hope all your worries are gone and everything you wish could find a place. Good morning!`",
    "`A great end may not be decided but a good creative beginning can be planned and achieved. Good morning, have a productive day!`",
    "`Having a sweet morning, a cup of coffee, a day with your loved ones is what sets your “Good Morning” have a nice day!`",
    "`Anything can go wrong in the day but the morning has to be beautiful, so I am making sure your morning starts beautiful. Good morning!`",
    "`Open your eyes with a smile, pray and thank god that you are waking up to a new beginning. Good morning!`",
    "`Morning is not only sunrise but A Beautiful Miracle of God that defeats the darkness and spread light. Good Morning.`",
    "`Life never gives you a second chance. So, enjoy every bit of it. Why not start with this beautiful morning. Good Morning!`",
    "`If you want to gain health and beauty, you should wake up early. Good Morning!`",
    "`Birds are singing sweet melodies and a gentle breeze is blowing through the trees, what a perfect morning to wake you up. Good morning!`",
    "`This morning is so relaxing and beautiful that I really don’t want you to miss it in any way. So, wake up dear friend. A hearty good morning to you!`",
    "`Mornings come with a blank canvas. Paint it as you like and call it a day. Wake up now and start creating your perfect day. Good morning!`",
    "`Every morning brings you new hopes and new opportunities. Don’t miss any one of them while you’re sleeping. Good morning!`",
    "`Start your day with solid determination and great attitude. You’re going to have a good day today. Good morning my friend!`",
    "`Friendship is what makes life worth living. I want to thank you for being such a special friend of mine. Good morning to you!`",
    "`A friend like you is pretty hard to come by in life. I must consider myself lucky enough to have you. Good morning. Wish you an amazing day ahead!`",
    "`The more you count yourself as blessed, the more blessed you will be. Thank God for this beautiful morning and let friendship and love prevail this morning.`",
    "`Wake up and sip a cup of loving friendship. Eat your heart out from a plate of hope. To top it up, a fork full of kindness and love. Enough for a happy good morning!`",
    "`It is easy to imagine the world coming to an end. But it is difficult to imagine spending a day without my friends. Good morning.`",
]

SLAP_TEMPLATES = (
    "{user2} was shot by {user1}.",
    "{user2} walked into a cactus while trying to escape {user1}.",
    "{user2} drowned whilst trying to escape {user1}.",
    "{user2} fell into a patch of cacti.",
    "{user2} went up in flames.",
    "{user2} burned to death.",
    "{user2} was burnt to a crisp whilst fighting {user1}.",
    "{user2} was struck by lightning.",
    "{user2} was slain by {user1}.",
    "{user2} was killed by magic.",
    "{user2} starved to death.",
    "{user2} fell out of the world.",
    "{user2} was knocked into the void by {user1}.",
    "{user2}'s bones are scraped clean by the desolate wind.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} says goodbye to this cruel world.",
    "{user2} got rekt.",
    "{user2} was sawn in half by {user1}.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2}'s death put another notch in {user1}'s axe.",
    "{user2} died from {user1}'s mysterious tropical disease.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user2} was shot before being thrown out of a plane.",
    "{user2} has encountered an error.",
    "{user2} died and reincarnated as a goat.",
    "{user1} threw {user2} off a building.",
    "{user2} got a premature burial.",
    "{user1} spammed {user2}'s email.",
    "{user1} hit {user2} with a small, interstellar spaceship.",
    "{user1} put {user2} in check-mate.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} died of hospital gangrene.",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user1} checkmated {user2} in two moves.",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!.",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2},Shinaeeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
)

HUG_TEMPLATES = (
    "{user1} {hug} {user2}.",
    "{user1} {hug} {user2} warmly.",
    "{user1} {hug} {user2} with a love. 💘",
    "{user1} {hug} {user2} with kindness.",
)

HUG = ("hugs", "hugged", "kissed", "pinches")

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)
